### ISSUE TITLE
Think of a system for extensions support

### ISSUE THREAD

**Issue by pawamoy** [shellm-org/core#6]
Example: I am now loading z.sh (from [z](https://github.com/rupa/z)). It is installed outside of my user repository. They should not be contained within the repo but somehow linked from it.

**Comment by Pawamoy** [comment]
Also see https://github.com/Pawamoy/shellm/issues/13

**Comment by pawamoy** [comment]
"Extensions" will now simply be wrappers. You want to make z available for shellm? Create a new shellm app with a dependency to z all related code to source it.
